### PR TITLE
fixes broken images with placeholder

### PR DESCRIPTION
**Pull request by irisdiakoumi**
adds a fix for when a product is created without adding an image url. it detects an error and adds a placeholder imag
item
feed_items
e

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @irisdiakoumi, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @irisdiakoumi! You're now able to merge the PR.

**Comment by irisdiakoumi** [comment]
DEAR GOD!

**Pull request merged**
